apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        runAsNonRoot: true 
        runAsUser: 33 #www-data user id as its default for ubuntu and user found in passwd file
        runAsGroup: 33 # same as above but for groups
        fsGroup: 33 #for volume mounts value same as above though
       # supplementalGroups: 4000

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports:
            - containerPort: 9090
         
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          
          securityContext:
           allowPrivilegeEscalation: false # can be false by default but good to set just in case

      volumes:
         - name: linkding-data
           persistentVolumeClaim:
             claimName: linkding-data-pvc
